In [15]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import numpy as np 

In [3]:
from sklearn.datasets import load_boston

In [4]:
df = load_boston()

/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func

In [6]:
df.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [8]:
df1=pd.DataFrame(df.data, columns = df.feature_names)

In [10]:
df1['Price'] = df.target

In [11]:
df1.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       Price  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.4 KB


In [13]:
df1.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
Price      0
dtype: int64

In [17]:
plt.plot(df1.CRIM,df1.Price)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [23]:
X = df1.iloc[:,:-1] 
Y = df1.iloc[:,-1]

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, x_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, random_state = 42)

In [28]:
X_train=scaler.fit_transform(X_train)

In [32]:
X_test = scaler.transform(x_test) 

In [33]:
from sklearn.linear_model import LinearRegression 

In [34]:
reg = LinearRegression()

In [35]:
reg.fit(X_train, Y_train)

LinearRegression()

In [36]:
reg.coef_

array([-1.10834602,  0.80843998,  0.34313466,  0.81386426, -1.79804295,
        2.913858  , -0.29893918, -2.94251148,  2.09419303, -1.44706731,
       -2.05232232,  1.02375187, -3.88579002])

In [39]:
y_test1= reg.predict(X_test)

In [42]:
plt.scatter(Y_test,y_test1) 
plt.xlabel('Test Truth Data')
plt.ylabel('Test Predicted Data')

Text(0, 0.5, 'Test Predicted Data')

In [43]:
residuals = Y_test - y_test1

Scatter Plot of Residual and Y_test


In [44]:
plt.scatter(y_test1,residuals)

Performance Metrics

In [46]:
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import mean_absolute_error

In [47]:
print(mean_squared_error(Y_test,y_test1))

21.5174442311772


In [50]:
print(mean_absolute_error(Y_test, y_test1))

3.1627098714574053


RMSE

In [53]:
print(np.sqrt(mean_squared_error(Y_test,y_test1)))

4.63868992617282


In [54]:
from sklearn.metrics import r2_score

In [56]:
score = r2_score(Y_test,y_test1)

In [57]:
score

0.7112260057484934

Ridge Regression 

In [58]:
from sklearn.linear_model import Ridge 
r = Ridge()   
r.fit(X_train,Y_train) 

Ridge()

In [59]:
r.coef_

array([-1.09593334,  0.78820029,  0.31413846,  0.81943277, -1.76159118,
        2.91992552, -0.30160552, -2.90234902,  2.01278255, -1.376115  ,
       -2.04111302,  1.02096425, -3.87116058])

In [60]:
r.alpha

1.0

In [61]:
y_pred=r.predict(X_test)

In [62]:
y_pred

array([28.62357833, 36.44550082, 15.52052973, 25.39268928, 18.84879558,
       23.14883229, 17.41574646, 14.11581949, 22.97626904, 20.62330821,
       24.7986272 , 18.56980064, -6.79651226, 21.82395903, 19.23236639,
       26.15383084, 20.17876099,  5.61962928, 40.38186486, 17.57457448,
       27.40479043, 30.10724265, 10.99655749, 24.03311622, 18.06162825,
       15.88868155, 23.13038253, 14.58160663, 22.34394126, 19.35560227,
       22.14342705, 25.19647555, 25.29564282, 18.49489607, 16.58510826,
       17.55589882, 30.95262083, 20.19997226, 23.91938314, 24.86566317,
       13.97663584, 31.73645514, 42.45771743, 17.66726076, 27.02329661,
       17.16789585, 13.84463969, 26.09882873, 20.27584009, 30.11423076,
       21.33675989, 34.10273722, 15.65044059, 26.13577945, 39.26685577,
       22.96438431, 18.95039756, 32.96838002, 24.85696548, 12.9626657 ,
       22.70164245, 30.77094825, 31.59045271, 16.32878007, 21.19256624,
       16.59236751, 20.34441547, 26.14494029, 31.01305592, 11.99

In [63]:
plt.scatter(Y_test,y_pred)

In [64]:
residual = Y_test-y_pred

In [65]:
residual

173    -5.023578
274    -4.045501
491    -1.920530
72     -2.592689
452    -2.748796
         ...    
441    -0.311825
23      1.067310
225    10.056158
433    -2.384659
447    -5.688907
Name: Price, Length: 152, dtype: float64

In [67]:
plt.scatter(residual,y_pred)

In [72]:
print(mean_squared_error(Y_test,y_pred)) 
print(mean_absolute_error(Y_test,y_pred))
print(np.sqrt(mean_squared_error(Y_test,y_pred))) 

21.5486535962302
3.161026516515536
4.642052735184102


In [74]:
from sklearn.metrics import r2_score 
r = r2_score(Y_test,y_pred) 

r

0.7108071617209415

In [75]:
from sklearn.linear_model import Lasso 

In [76]:
lasso = Lasso(alpha = 0.5) 

In [82]:
lasso.fit(X_train,Y_train)

Lasso(alpha=0.5)

In [83]:
lasso.alpha

0.5

In [84]:
lasso.coef_

array([-0.29690752,  0.        , -0.        ,  0.59285964, -0.        ,
        2.97804837, -0.        , -0.25171146, -0.        , -0.        ,
       -1.500692  ,  0.61113716, -3.85772338])

In [85]:
lasso.fit

<bound method ElasticNet.fit of Lasso(alpha=0.5)>

In [87]:
y_pred= lasso.predict(X_test)

In [88]:
plt.scatter(Y_test,y_pred) 

In [89]:
residuals = y_pred - Y_test

In [90]:
plt.scatter(residuals,y_pred)

In [95]:
print('Mean sqaured error is {}'.format(mean_squared_error(y_pred,Y_test))) 
print('Mean absolute error is {}'.format(mean_absolute_error(y_pred,Y_test))) 
print('RMSE is {}'.format(np.sqrt(mean_squared_error(y_pred,Y_test))))

Mean sqaured error is 25.343992307954153
Mean absolute error is 3.473208874380659
RMSE is 5.034281707250217


In [97]:
r = r2_score(y_pred,Y_test)

In [98]:
r

0.47004320743842887

In [99]:
from sklearn.linear_model import ElasticNet 

In [100]:
e=ElasticNet(alpha =1.0)

In [101]:
e.fit(X_train,Y_train)

ElasticNet()

In [102]:
e.get_params

<bound method BaseEstimator.get_params of ElasticNet()>

In [103]:
e.max_iter

1000

In [104]:
e.coef_

array([-0.44133869,  0.        , -0.17947169,  0.59692089, -0.18716495,
        2.39933243, -0.        , -0.        , -0.        , -0.2673279 ,
       -1.24862802,  0.54019223, -2.5317966 ])

In [105]:
y_pred = e.predict(X_test)

In [106]:
y_pred

array([26.12464007, 31.08359511, 18.04597272, 24.70380069, 19.18374056,
       23.04828156, 19.87776448, 16.44914858, 20.93514561, 21.08127078,
       23.52550978, 22.44635623,  2.24189576, 22.84104954, 21.05280073,
       23.58296191, 19.30073257,  9.1447913 , 34.67793046, 18.35121592,
       25.4226821 , 26.56739378, 16.06078701, 23.76499121, 18.25531091,
       15.81421549, 22.85868186, 17.52025286, 22.72401432, 20.38251848,
       21.29714101, 25.1119618 , 23.31252729, 18.5407437 , 16.66553998,
       20.31514452, 29.87595921, 22.12166637, 23.92965792, 24.49404428,
       16.52214338, 27.35152214, 35.05354693, 20.69784204, 25.61890333,
       17.26925598, 17.5258844 , 25.4074854 , 19.4251224 , 28.83677113,
       23.89456126, 30.73445986, 19.10027687, 25.17490354, 33.62949333,
       21.92453505, 19.1575743 , 28.43548121, 24.95114561, 18.65244631,
       25.48043619, 30.05952777, 27.84122673, 18.66579198, 26.87470934,
       18.60024826, 19.70073997, 25.39065172, 27.69833527, 15.18

In [107]:
plt.scatter(Y_test,y_pred)

In [108]:
print('Mean sqaured error is {}'.format(mean_squared_error(y_pred,Y_test))) 
print('Mean absolute error is {}'.format(mean_absolute_error(y_pred,Y_test))) 
print('RMSE is {}'.format(np.sqrt(mean_squared_error(y_pred,Y_test))))

Mean sqaured error is 27.49013125457783
Mean absolute error is 3.6468704439752937
RMSE is 5.2431032084613625


In [109]:
r = r2_score(y_pred,Y_test)

In [110]:
r

0.158481483340688